---
layout: cv
title: Xave Perry 's Resume
---
# Brigham Young
Computer Science Major at Brigham Young University - Idaho

<div id="webaddress">
<a href="perrshan2001@byui.edu">perrshan2001@byui.edu</a>
| <a href="https://github.com/Perrshan/DS250">Data Science Program</a>
| <a href="https://www.linkedin.com/in/xave-perry/">LinkedIn</a>
| <a href="https://github.com/Perrshan/DS250">GitHub</a>
</div>

<!-- https://www.monique.tech/the-art-of-markdown -->

## Education

`2017-2020`
__Idaho State University__, Pocatello, ID

- A.A in General Studies with a 3.89 GPA

`Expected 2025`
__Brigham Young University - Idaho__, Rexburg, ID

- BS degree in Computer Science with a 3.80 GPA
- Minor in Computer Engineering

## Skills

- Languages: Python, C, C#, MySQL, Erlang, Javascript, HTML, CSS, Rust

- Software Tools: Visual Studio Code, Tableau, Logism-Evolution, LTspice, STM Cube IDE, Eclipse

## School Projects

- Designed a slide puzzle using C and a nucleo-I476 board
- Created a 4-bit CPU to do basic math and display characters and numbers
- Made an object-oriented banking program in C# using abstraction, encapsulation, inheritance, and polymorphism
- Created a basic network game that multiple players can connect to a play using Python and TCP connections.

## Service and Work History

`2023-2024`
__Customer Care Representative__, Melaleuca

- Achieved Star Performer amongst all of the other customer care representatives
- Earned a score within the top 20% of the other agents two months in a row
- Chosen to be one of the few agents to take extra calls on the Riverbend Ranch phone
line
- Improved my average handle time increasing my volume of phone calls so that I
could efficiently help more people each day

`2022-2023`
__Custodian__, Honest Cleaning

- Cleaned a dental office and a plasma donation center both needing great attention to
detail to keep patients and employees safe in medical environments
- Applied feedback diligently to improve cleaning efforts to maintain building
cleanliness according to the desired expectations of clients and employer
- Planned hours of work to get all buildings ready for following day's activities and
never received any complaints keeping clients happy

`2020-2022`
__Service Missionary__, Austin, Texas

- Worked and served 11 hours a day 6 days a week setting up appointments and teaching others
- Kept an up to date data source that recorded all contacts that I had with those around me
- Helped manage a Facebook page owned by the mission

`2018-2020`
__Team Lead__, Car Wash Express

- Led team to complete daily requirements and made sure all tasks were done
professionally and correctly
- Entrusted with quickly troubleshooting issues causing cars to not be washed as to
maintain customer safety and satisfaction by rebooting systems or clearing the path
of the conveyor belt
- Promoted seasonal savings by explaining promotions and encouraging clients to
purchase offers and was always a top seller

<!-- ### Footer

Last updated: May 2013 -->
